version: '3.3'

networks:
  fastapi_network:
    external:
      name: fastapi_network

services:

    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379

    api:
        build:
            context: .
            dockerfile: Dockerfile
        #image: fastapi-test-img:0.0.1
        volumes:
            - ./:/app/
        command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
        depends_on:
            - redis
        env_file:
            - ./.env
        ports:
            - 8008:8000
        networks:
            - fastapi_network


